In [53]:
def readpdf(file):
    data = ""
    with pdfplumber.open(file) as pdf:
        for page in pdf.pages:
            data = str(page.extract_text()) + data
    return data

In [54]:
import os, textract
import pdfplumber
import re
import numpy as np

In [55]:
path = r"C:\Users\dines\Music\Work\resumeParser\com"

In [56]:
text = []
labels = []
for paths, subdirs, files in os.walk(path):
    if paths.split("\\")[-1] == "CVs":
        for file in files:
            if file.split(".")[-1] == "pdf":
                text.append(readpdf(os.path.join(paths, file)))
            else:
                a = textract.process(os.path.join(paths, file))
                text.append(a.decode("utf-8"))
            labels.append(0)
    else:
        for file in files:
            if file.split(".")[-1] == "pdf":
                text.append(readpdf(os.path.join(paths, file)))
            else:
                a = textract.process(os.path.join(paths, file))
                text.append(a.decode("utf-8"))
            labels.append(1)

In [57]:
def textpreprocessing(text):
    text = text.lower()
    text = re.sub("[!#$^*-.=[[]]+//*<>?;:~`0-9", "", text)
    text = " ".join(text.split())
    return text

In [58]:
X = []
for t in text:
    X.append(textpreprocessing(t))

In [59]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [60]:
cv = CountVectorizer()
X = cv.fit_transform(X).toarray()

In [61]:
X.shape

(228, 19917)

In [62]:
y = np.array(labels)

In [63]:
from sklearn.utils import shuffle

In [64]:
X, y = shuffle(X, y)

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [67]:
print(X_train.shape, y_train.shape)

(193, 19917) (193,)


In [68]:
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

In [69]:
svc = SVC()
svc.fit(X_train, y_train)

SVC()

In [70]:
svc.predict(X_test)

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0])

In [71]:
y_test

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1])

In [84]:
file1 = r"C:\Users\dines\Pictures\files\Dinesh y SEP'20.pdf"

In [85]:
test = readpdf(file1)

In [86]:
test = textpreprocessing(test)

In [87]:
test = cv.transform([test]).toarray()
svc.predict(test)

array([0])